apiVersion: v1
kind: ConfigMap
metadata:
  name: opencrvs-confmap
data:
  HOST: "0.0.0.0"
  WEBHOOK_URL: "https://webhooks.___OPENCRVS_ROOT_DOMAIN___/webhooks"
  AUTH_URL: "https://auth.___OPENCRVS_ROOT_DOMAIN___/"
  CALLBACK_URL: "https://___MOSIP_API_PUBLIC_HOST___/opencrvs-mediator/webhooks"
---
apiVersion: v1
kind: Secret
metadata:
  name: opencrvs-client
type: Opaque
data:
  CLIENT_ID: ___CLIENT_ID___
  CLIENT_SECRET: ___CLIENT_SECRET___
  SHA_SECRET: ___SHA_SECRET___
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencrvs-out-data-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencrvs-mediator
  labels:
    app: opencrvs-mediator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencrvs-mediator
  template:
    metadata:
      labels:
        app: opencrvs-mediator
    spec:
      containers:
      - name: mediator
        image: lalithkota/mosip-opencrvs-mediator:develop
        ports:
        - containerPort: 4545
          name: http
          protocol: TCP
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: opencrvs-confmap
        - secretRef:
            name: opencrvs-client
        volumeMounts:
        - mountPath: "/mnt/data"
          name: pvc-for-out-data
      volumes:
      - name: pvc-for-out-data
        persistentVolumeClaim:
          claimName: opencrvs-out-data-claim
---
apiVersion: v1
kind: Service
metadata:
  name: opencrvs-mediator
  labels:
    app: opencrvs-mediator
spec:
  selector:
    app: opencrvs-mediator
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: opencrvs
  labels:
    app: opencrvs-mediator
spec:
  gateways:
  - istio-system/public
  hosts:
  - '*'
  http:
  - headers:
      request:
        set:
          x-forwarded-proto: https
    match:
    - uri:
        exact: /opencrvs-mediator/birth
    rewrite:
      uri: /birth
    route:
    - destination:
        host: opencrvs-mediator
        port:
          number: 80
